name: Publisher

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn
        if: >
          github.event.pull_request.merged == true &&
          github.event.pull_request.base.ref == 'master' &&
          !startsWith(github.event.pull_request.head.ref, 'renovate/')

      - name: Configure GPG Key
        run: |
          mkdir -p ~/.gnupg/
          printf "$GPG_SIGNING_KEY" | base64 --decode > ~/.gnupg/private.key
          gpg --import ~/.gnupg/private.key
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}

      - name: Configure Git
        run: |
          git config --local user.email $GIT_EMAIL
          git config --local user.name $GIT_USER
          git config --local user.signingkey $GPG_KEY_ID
          git config --local commit.gpgsign true
        env:
          GIT_USER: ${{ secrets.GIT_USER }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID}}

  release:
    needs: build
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Create Release
        run: |
          yarn install
          yarn lerna version --no-git-tag-version --yes
          git add .
          git commit -m 'chore(release): %s'
          git push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Config NPM
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/

      - name: Publish to NPM
        run: yarn lerna publish from-package --no-verify-access --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Config GPR
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          scope: ${{ secrets.SCOPE }}

      - name: Publish to GPR
        run: yarn lerna publish from-package --no-verify-access --yes -m "chore(release)"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
